[package]
name = "awecut"
version = "0.1.0"
edition = "2024"
authors = ["FuseTim"]
license = "GPL-3.0-or-later"
description = "awecut - say bye to the TV commercials"

[dependencies]
rustfft = "6.3.0"
